#!/bin/sh
APP_DIR=`dirname $0`
APP_DIR=`cd "$APP_DIR";pwd`
export LD_LIBRARY_PATH=$DIR/usr/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="${APP_DIR}/usr/lib/:${APP_DIR}/usr/lib/i386-linux-gnu/:${APP_DIR}/usr/lib/x86_64-linux-gnu/:${APP_DIR}/usr/lib32/:${APP_DIR}/usr/lib64/:${APP_DIR}/lib/:${APP_DIR}/lib/i386-linux-gnu/:${APP_DIR}/lib/x86_64-linux-gnu/:${APP_DIR}/lib32/:${APP_DIR}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="${APP_DIR}/usr/lib/python3.8/site-packages/"
export PATH=$DIR/usr/bin:$PATH
exec "$APP_DIR/usr/bin/token-manager" "$@"